// app/constants.ts
import { ViewType, StatusFilterMode } from '../types'; // ViewType wird immer noch für VIEW_TITLES benötigt









// Definiere ein Interface für alle API Endpunkte, um den TypeScript-Fehler zu beheben
interface AllApiEndpoints {
    beschwerden: string;
    lob: string;
    anregungen: string;
    statistik: string;
    admin?: string; // Admin ist optional oder kann einen leeren String haben, wenn kein direkter Datenendpunkt
    login: string;
    verifyToken: string;
    createUser: string;
}







export const API_ENDPOINTS: AllApiEndpoints = {
    beschwerden: '/api/containt',
    lob: '/api/like',
    anregungen: '/api/feedback',
    statistik: '/api/statistics',
    admin: '',
    login: '/api/login',
    verifyToken: '/api/verify-token',
    createUser: '/api/admin/create-user',
};




export const VIEW_TITLES: Record<ViewType, string> = {
    beschwerden: "Beschwerdeübersicht",
    lob: "Lobübersicht",
    anregungen: "Anregungsübersicht",
    statistik: "Statistiken & Analyse",
    admin: "Administration",
};





export const FILTER_LABELS: Record<StatusFilterMode, string> = {
    alle: "Alle",
    Offen: "Offen",
    "In Bearbeitung": "In Bearbeitung",
    Gelöst: "Gelöst",
    Abgelehnt: "Abgelehnt",
};




export const LOGIN_APP_NAME = "BM";
export const COMPANY_NAME = "Cottbusverkehr";
export const COMPANY_SUBTITLE = "Ein Unternehmen der Stadt Cottbus/Chóśebuz";
// LOGIN_API_ENDPOINT Konstante wird nicht mehr separat benötigt, da sie in API_ENDPOINTS.login enthalten ist.
// export const LOGIN_API_ENDPOINT = '/api/login'; // Entfernt oder auskommentiert





export const ALLE_LINIEN: string[] = [
    "1",
    "2",
    "3",
    "4",
    "10",
    "12",
    "15",
    "16",
    "19",
    "21",
    "22",
    "29",
    "3N",
    "4N",
    "47",
    "EV1",
    "EV2",
    "EV3",
    "EV4"
];

export const ALLE_HALTESTELLEN: string[] = [
    "Abzweig Steinteichmühle",
    "Albrecht-Dürer-Straße",
    "Altmarkt",
    "Am Doll",
    "Am Fließ",
    "Am Hammergraben",
    "Am Lug",
    "Am Nordrand",
    "Am Priorgraben",
    "Am Seegraben",
    "Am Zollhaus",
    "Amselweg",
    "An der Pastoa",
    "An der Pastoa (BM Ortsumg. Linie 849)",
    "Anne-Frank-Straße (Mobil Südnetz)",
    "August-Bebel-Straße",
    "Ausbesserungswerk",
    "Ärztehaus Uhlandstraße (Mobil Südnetz)",
    "Bärenbrücker Straße",
    "Beuchstraße",
    "Bleyerstraße",
    "Bonnaskenplatz",
    "Branitz Auenwinkel",
    "Branitz Park",
    "Branitz Rosenwinkel",
    "Branitz Schloss",
    "Branitz Alte Schule",
    "Branitz Waldesruh",
    "Branitz Wappenhaus",
    "Branitz Zum Seebad",
    "Branitzer Siedlung",
    "Burger Chaussee / TIP",
    "Burger Chaussee Campus Nord",
    "Burger Chaussee Süd",
    "Byhlener Straße",
    "Carl-Blechen-Park",
    "Carl-von-Ossietzky-Straße",
    "Chopinstraße",
    "Clara-Zetkin-Straße",
    "Cottbus Center",
    "Europaschule (Mobil Südnetz)",
    "Dissenchen Ausbau",
    "Dissenchen Birkenstraße",
    "Dissenchen Haasower Straße",
    "Dissenchen Schule",
    "Dissenchen Turnstraße",
    "Dissenchen Wendeplatz",
    "Dissenchener Straße",
    "Döbbrick Altes Dorf",
    "Döbbrick Am Spreebogen",
    "Döbbrick Dissener Weg",
    "Döbbrick, Dissener Weg",
    "Döbbricker Dorfstraße",
    "Döbbrick Kiebitzweg",
    "Döbbrick Kirche",
    "Döbbrick Ost",
    "Döbbrick Süd",
    "Döbbrick Wiesengrund",
    "Döbbrick Zum Landgraben",
    "Döbbrick Zur Rehwiese",
    "Drewitzer Straße",
    "Eigene Scholle",
    "Ewald-Müller-Straße",
    "Elisabeth-Wolf-Straße",
    "Feuerbachstraße",
    "Baumuniversität",
    "Finkenweg",
    "Finsterwalder Straße",
    "Flugplatzmuseum",
    "Freiheitsstraße",
    "Freizeitbad Lagune",
    "Friedrich-Hebbel-Straße",
    "Friedrich-List-Straße (EV)",
    "Friedrich-List-Straße",
    "G.-Schlesinger-Straße",
    "Gallinchen Am Eichengrund",
    "Gallinchen Behindertenwerkstatt",
    "Gallinchen Friedensplatz",
    "Gallinchen Gaglower Straße",
    "Gallinchen Kutzeburger Weg",
    "Gallinchen Parzellenstraße",
    "Gallinchen Schorbuser Weg",
    "Gallinchen Siedlung",
    "Gallinchen Sportpark",
    "Gallinchen Spreemarkt",
    "Gallinchen Telering",
    "Gartenstraße (Messeverkehr)",
    "Gelsenkirchener Platz A",
    "Gelsenkirchener Platz B",
    "Gelsenkirchener Platz C",
    "Gelsenkirchener Platz D",
    "Gelsenkirchener Platz E",
    "Gelsenkirchener Platz F",
    "Gelsenkirchener Platz (Mobil Südnetz)",
    "Gerhart-Hauptmann-Straße",
    "Geschw.-Scholl-Straße",
    "Gewerbeweg",
    "Goethestraße",
    "Görlitzer Straße",
    "Goyatzer Straße",
    "Groß Gaglow, Autobahnbrücke",
    "Groß Gaglow Chausseestraße",
    "Groß Gaglow Harnischdorfer Straße",
    "Groß Gaglow Harnischdorfer Straße (Mobil Südnetz)",
    "Groß Gaglow Lausitz-Park",
    "Groß Gaglow Sachsendorfer Straße",
    "Groß Gaglow Schule",
    "Guhrower Straße/Cottbus Center",
    "Hammergrabensiedlung",
    "Hauptbahnhof",
    "Hauptbahnhof (Stadtring)",
    "Hauptbahnhof (Bussteig 1-9)",
    "Hans-Beimler-Straße",
    "Heidesiedlung",
    "Heinrich-Hertz-Straße",
    "Heinrich-Mann-Straße",
    "Hermannstraße",
    "Heizkraftwerk",
    "Hermann-Hammerschmidt-Straße",
    "Hermann-Hammerschmidt-Straße (2N)",
    "Hermann-Löns-Straße",
    "Hölderlinstraße",
    "Hubertstraße",
    "Hufelandstraße",
    "Jessener Straße",
    "Jessener Straße (Nur zum Ausstieg)",
    "Juri-Gagarin-Straße",
    "Kahren Am Lehrerhaus",
    "Kahren Am Park",
    "Kahren Am Sportplatz",
    "Kahren Karlshof",
    "Kahren Kirche",
    "Kahren Neuhausener Weg",
    "Kahren Schmiede",
    "Kahren Schule",
    "Kauperstraße",
    "Kiekebusch Büdnerstraße",
    "Kiekebusch Friedhof",
    "Kiekebuscher Hauptstraße",
    "Kiekebusch Kiefernweg",
    "Kiekebusch Schule",
    "Klein Ströbitz",
    "Kleiststraße",
    "Kornblumenweg",
    "Lakoma",
    "Lauchhammer Straße",
    "Lipezker Straße/Schwarzheider Straße",
    "Lortzingstraße",
    "Lutherstraße (EV)",
    "M.-Domaskojc-Straße / Gymnasium",
    "M.-Domaskojc-Straße",
    "Madlow",
    "Madlow Gaglower Landstraße",
    "Madlow Hänchener Straße",
    "Maiberg Friedhof",
    "Maiberg Mitte",
    "Maiberg Ost",
    "Marienstraße/GladHouse",
    "Marjana-Domaskojc-Straße",
    "Max-Grünebaum-Straße",
    "Meisenweg",
    "Merzdorfer Alpen",
    "Merzdorf Alter Bahnhof",
    "Merzdorf Feuerwehr",
    "Merzdorf Cottbuser Ostsee",
    "Merzdorf Tranitzfließ",
    "Merzdorf Tranitzfließ (Mobil)",
    "Merzdorf West (Rück Schild)",
    "Merzdorfer Bahnhofstraße",
    "Merzdorfer Weg",
    "Messehallen (Messeverkehr)",
    "Neu Schmellwitz",
    "Neu Schmellwitz Zuschka",
    "Neue Straße",
    "Neue Straße (EV)",
    "Neue Straße  (4N)",
    "Neue Straße (Schulbus)",
    "Neuhausener Straße",
    "Nordfriedhof",
    "Nordparkstraße",
    "Nordring",
    "Ostseedorf Schlichow",
    "Ottilienstraße",
    "Papitzer Straße",
    "Peitzer Straße",
    "Platz der Freundschaft",
    "Potsdamer Straße",
    "Poznaner Straße/ BTU",
    "Priorstraße",
    "Quellgrund",
    "Rennbahnweg",
    "Ringstraße",
    "Rosa-Luxemburg-Straße",
    "Saarbrücker Straße",
    "Sachsendorf Hegelstraße",
    "Sachsendorf",
    "Sachsendorf Waldweg",
    "Sachsendorfer Hauptstraße",
    "Sandow Warmbad",
    "Sandow Wendeschleife",
    "Sandower Dreieck (EV/ODEG)",
    "Saspow Fröbelstraße",
    "Saspow Kleine Straße",
    "Saspow Schreberweg",
    "Schillerstraße",
    "Schlichower Dorfstraße",
    "Schlichower Höhe",
    "Schmellwitz Anger",
    "Schmellwitz Anger/Feldstraße",
    "Schmellwitzer Straße",
    "Schmellwitzer Weg",
    "Schwarzheider Straße",
    "Siedlerstraße",
    "Sielow Am Ring",
    "Sielow Fehrower Weg",
    "Sielow Feuerwehr",
    "Sielow Mühle",
    "Sielow Sportplatz",
    "Sielow Sportplatz (Nur zum Ausstieg)",
    "Sielow Striesower Straße",
    "Sielow Erlengrund",
    "Sielow Windmühlenweg",
    "Skadow",
    "Spitzwegstraße",
    "Sportpalast",
    "Sportzentrum",
    "Spreestraße",
    "Spreewaldbahnhof",
    "Spreewehrmühle",
    "Stadthalle (Rathaus) E",
    "Stadthalle (Rathaus) F",
    "Stadthalle Puschkinpromenade C",
    "Stadthalle Puschkinpromenade D",
    "Stadthalle Post A",
    "Stadthalle Post B",
    "Stadtmuseum",
    "Stadtpromenade A",
    "Stadtpromenade B",
    "Stadtpromenade C",
    "Stadtpromenade D",
    "Stadtring",
    "Stadtverwaltung",
    "Steinteichmühle",
    "Straupitzer Straße",
    "Ströbitz Friedhof",
    "Ströbitzer Hauptstraße",
    "Ströbitz (3N)",
    "Ströbitz Wendeschleife",
    "Ströbitz Mühlenweg",
    "Ströbitz Ziegelstraße",
    "Ströbitzer Schulstraße",
    "Ströbitzer Weg",
    "Studentenweg",
    "Südfriedhof",
    "Südeck",
    "Thiemstraße Schleife",
    "Thiemstraße/Klinikum",
    "Thierbacher Straße",
    "Tierpark",
    "Tierpark (Nur zum Ausstieg)",
    "Uhlandstraße",
    "Universität",
    "Universitätsbibliothek",
    "Vetschauer/Leipziger Straße",
    "Vetschauer/Leipziger Straße (EV)",
    "Viehmarkt",
    "Vom-Stein-Straße",
    "Vorpark",
    "Waisenstraße",
    "Warschauer Straße",
    "Weinbergstraße",
    "Welzower Straße/Klinikum",
    "Welzower Straße/Thiemstraße",
    "Wilhelm-Nevoigt-Platz",
    "Willmersdorf Jahnstraße",
    "Willmersdorf Möbeldorf",
    "Willmersdorf Neu Lakoma",
    "Willmersdorf Turnweg",
    "Zahsower Straße/Sportplatz",
    "Zielona-Gora-Straße",
    "Zimmerstraße"
];

export const COMPLAINT_REASONS = [
    "Ausgefallene Fahrt",
    "Verspätete Fahrt",
    "Verfrühte Fahrt",
    "Nicht befördert",
    "Fahrplanangebot",
    "Service und Verkauf",
    "Fahrverhalten",
    "Ausgelassene Haltestelle",
    "Fehlende Anschlussgewährung",
    "Ordnung und Sauberkeit",
    "Technische Störung",
    "Informationen und Veröffentlichung",
    "Verhalten Personal",
    "Sonstige"
];

export const REASONS_REQUIRING_LINE_AND_STATION = [
    "Ausgefallene Fahrt",
    "Verspätete Fahrt",
    "Verfrühte Fahrt",
    "Ausgelassene Haltestelle",
    "Nicht befördert",
    "Fahrverhalten",
    "Fehlende Anschlussgewährung",
];
